# production_config.py
# (Your existing constants)

DAILY_RESET_WINDOW_HOURS = 24
SESSION_TIMEOUT_MINUTES = 60
FINGERPRINT_TIMEOUT_SECONDS = 20 # Keep at 20 seconds, the JS will use this
TIER_1_BAN_HOURS = 1
TIER_2_BAN_HOURS = 24
EMAIL_VERIFIED_BAN_HOURS = 24
GUEST_QUESTION_LIMIT = 4
EMAIL_VERIFIED_QUESTION_LIMIT = 10
REGISTERED_USER_QUESTION_LIMIT = 20
REGISTERED_USER_TIER_1_LIMIT = 10
RATE_LIMIT_REQUESTS = 15
RATE_LIMIT_WINDOW_SECONDS = 60
MAX_MESSAGE_LENGTH = 1000
MAX_PDF_MESSAGES = 50
MAX_FINGERPRINT_CACHE_SIZE = 1000
MAX_RATE_LIMIT_TRACKING = 1000
MAX_ERROR_HISTORY = 500
CRM_SAVE_MIN_QUESTIONS = 2
EVASION_BAN_HOURS = 72

# FastAPI Endpoints
# IMPORTANT: Update these with your actual deployed FastAPI URLs
FASTAPI_EMERGENCY_SAVE_URL = "https://fifi-beacon-fastapi-121263692901.europe-west4.run.app/emergency-save"
FASTAPI_FINGERPRINT_URL = "https://fifi-beacon-fastapi-121263692901.europe-west4.run.app/fingerprint" # NEW: For client-side fingerprinting
FASTAPI_EMERGENCY_SAVE_TIMEOUT = 5 # seconds

# Time Deltas (derived from hours/minutes for convenience)
DAILY_RESET_WINDOW = timedelta(hours=DAILY_RESET_WINDOW_HOURS)
SESSION_TIMEOUT_DELTA = timedelta(minutes=SESSION_TIMEOUT_MINUTES)
