[logger]
level = "debug"

[server]
# Port configuration
port = 8501
address = "0.0.0.0"

# Disable protections since nginx handles security
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

# Increase limits for JavaScript components
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Server configuration for internal communication
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[runner]
# Enable magic for component communication
magicEnabled = true
fastReruns = true

[client]
# Show detailed errors for debugging
showErrorDetails = true
toolbarMode = "minimal"

[theme]
primaryColor = "#e6007e"
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f3f3"
textColor = "#31333F"
font = "sans serif"

# Note: showWidgetBorder was removed in newer Streamlit versions
# If you're using an older version, uncomment the next line:
# showWidgetBorder = true

[theme.sidebar]
borderColor = "#e6007e"
