[logger]
level = "debug"

[server]
enableXsrfProtection = false

[client]
showErrorDetails = true

# Enable CORS and explicitly set the CSP header for maximum compatibility.
enableCORS = false
corsAllowedOrigins = ['https://www.12taste.com/', 'https://12taste.com/', 'https://cdn.jsdelivr.net/', 'https://fpjscdn.net/', 'https://api.fpjs.io/', 'https://fifi-eu-121263692901.europe-west1.run.app/']

[theme]
primaryColor = "#e6007e"
base = "light"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f3f3"
textColor = "#31333F"
font = "sans serif"
showWidgetBorder = true

[theme.sidebar]
borderColor = "#e6007e"
